interface CordovaPlugins {
  settings: NativeSettingsPlugin;
}

interface NativeSettingsPlugin {
  open(
    setting: SettingsOption | [SettingsOption, boolean],
    onsucess?: (result: string) => void,
    onfail?: (error: string) => void,
  ): void;
}

type SettingsOption = SettingsOptionAndroid | SettingsOptionIOS;

type SettingsOptionAndroid =
  | 'accessibility'
  | 'account'
  | 'airplane_mode'
  | 'apn'
  | 'application_details'
  | 'application_development'
  | 'application'
  | 'battery_optimization'
  | 'bluetooth'
  | 'captioning'
  | 'cast'
  | 'data_roaming'
  | 'date'
  | 'display'
  | 'dream'
  | 'home'
  | 'keyboard'
  | 'keyboard_subtype'
  | 'locale'
  | 'location'
  | 'manage_all_applications'
  | 'manage_applications'
  | 'memory_card'
  | 'network'
  | 'nfcsharing'
  | 'nfc_payment'
  | 'nfc_settings'
  | 'notification_id'
  | 'print'
  | 'privacy'
  | 'quick_launch'
  | 'search'
  | 'security'
  | 'settings'
  | 'show_regulatory_info'
  | 'sound'
  | 'storage'
  | 'store'
  | 'sync'
  | 'usage'
  | 'user_dictionary'
  | 'voice_input'
  | 'wifi_ip'
  | 'wifi'
  | 'wireless';

type SettingsOptionIOS =
  | 'about'
  | 'accessibility'
  | 'account'
  | 'airplane_mode'
  | 'application_details'
  | 'autolock'
  | 'battery'
  | 'bluetooth'
  | 'browser'
  | 'castle'
  | 'cellular_usage'
  | 'configuration_list'
  | 'date'
  | 'display'
  | 'do_not_disturb'
  | 'facetime'
  | 'keyboard'
  | 'keyboards'
  | 'locale'
  | 'location'
  | 'locations'
  | 'mobile_data'
  | 'music'
  | 'music_equalizer'
  | 'music_volume'
  | 'network'
  | 'nike_ipod'
  | 'notes'
  | 'notification_id'
  | 'passbook'
  | 'phone'
  | 'photos'
  | 'privacy'
  | 'reset'
  | 'ringtone'
  | 'search'
  | 'settings'
  | 'sound'
  | 'software_update'
  | 'storage'
  | 'store'
  | 'tethering'
  | 'touch'
  | 'tracking'
  | 'twitter'
  | 'usage'
  | 'video'
  | 'vpn'
  | 'wallpaper'
  | 'wifi';
